# Generated by Django 3.2.7 on 2021-11-03 20:21

import core.express.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('ci_attendant', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CI')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CI/Pasaporte')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('fly', models.CharField(max_length=50, verbose_name='Vuelo')),
                ('agency', models.CharField(max_length=50, verbose_name='Agencia')),
                ('arrive_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha LLegada')),
                ('leave_date', models.DateField(verbose_name='Fecha Salida')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dpt', models.CharField(max_length=50, verbose_name='Nombre Dpt')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Teléfono Dpt')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('ci_executive', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CI ejecutivo')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('user_name', models.CharField(max_length=11, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ejecutivo',
                'verbose_name_plural': 'Ejecutivos',
            },
        ),
        migrations.CreateModel(
            name='KindRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kind', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipo de Reportes',
            },
        ),
        migrations.CreateModel(
            name='Observ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observ_name', models.CharField(max_length=120, unique=True, verbose_name='Nombre de Estancia')),
            ],
            options={
                'verbose_name': 'Estancia',
                'verbose_name_plural': 'Estancias',
            },
        ),
        migrations.CreateModel(
            name='Responce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_state', models.CharField(max_length=120, unique=True, verbose_name='Estado Habitación')),
            ],
            options={
                'verbose_name': 'Estado Habitación',
                'verbose_name_plural': 'Estado Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=core.express.models.Room.room_number, verbose_name='No Hab.')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='express.roomstate', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_number', models.AutoField(primary_key=True, serialize=False, verbose_name='No.')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('get_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de recibo')),
                ('top_date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha tope')),
                ('response_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('responsed', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('agree', models.BooleanField(default=False, verbose_name='Conforme')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.attendant', verbose_name='Encargado')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.executive', verbose_name='Ejecutivo')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.kindrep', verbose_name='Tipo de reporte')),
                ('responce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='express.responce', verbose_name='Respuesta')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='ClientRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha hospedaje')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='express.client', verbose_name='Cliente')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.room', verbose_name='No. Hab')),
            ],
            options={
                'verbose_name': 'Habitación Cliente',
                'verbose_name_plural': 'Habitación Clientes',
            },
        ),
        migrations.CreateModel(
            name='ClientOb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observ_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha estancia')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.client', verbose_name='Cliente')),
                ('observ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.observ', verbose_name='Estancia')),
            ],
            options={
                'verbose_name': 'Estancia Cliente',
                'verbose_name_plural': 'Estancias Clientes',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='observations',
            field=models.ManyToManyField(through='express.ClientOb', to='express.Observ', verbose_name='Estancia'),
        ),
        migrations.AddField(
            model_name='client',
            name='rooms',
            field=models.ManyToManyField(through='express.ClientRoom', to='express.Room'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='dpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.departament', verbose_name='Departamento'),
        ),
    ]
