# Generated by Django 3.2.5 on 2021-09-23 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CI/Pasaporte')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('fly', models.CharField(max_length=50, verbose_name='Vuelo')),
                ('agency', models.CharField(max_length=50, verbose_name='Agencia')),
                ('arrive_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha LLegada')),
                ('leave_date', models.DateField(verbose_name='Fecha Salida')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
