# Generated by Django 3.2.7 on 2021-09-23 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientObs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observ_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Observación')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de asignación')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CI/Pasaporte')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('fly', models.CharField(max_length=50, verbose_name='Vuelo')),
                ('agency', models.CharField(max_length=50, verbose_name='Agencia')),
                ('arrive_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha LLegada')),
                ('leave_date', models.DateField(verbose_name='Fecha Salida')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='RoomStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_state', models.CharField(max_length=300, verbose_name='Estado Habitación')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('number', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Número habitación')),
                ('client', models.ManyToManyField(through='express.ClientRoom', to='express.Clients')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.roomstates')),
            ],
        ),
        migrations.CreateModel(
            name='Observs',
            fields=[
                ('observ_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('observ_name', models.CharField(max_length=300, verbose_name='Observación')),
                ('clients', models.ManyToManyField(through='express.ClientObs', to='express.Clients')),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
            },
        ),
        migrations.AddField(
            model_name='clientroom',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.clients'),
        ),
        migrations.AddField(
            model_name='clientroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.rooms'),
        ),
        migrations.AddField(
            model_name='clientobs',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.observs'),
        ),
        migrations.AddField(
            model_name='clientobs',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express.clients'),
        ),
    ]
