# Generated by Django 3.2.7 on 2021-09-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendants',
            options={'verbose_name': 'Encargado', 'verbose_name_plural': 'Encargados'},
        ),
        migrations.AlterModelOptions(
            name='clientob',
            options={'verbose_name': 'Observ Cliente', 'verbose_name_plural': 'Observ Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientroom',
            options={'verbose_name': 'Habitación Cliente', 'verbose_name_plural': 'Habitación Clientes'},
        ),
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='executive',
            options={'verbose_name': 'Ejecutivo', 'verbose_name_plural': 'Ejecutivo'},
        ),
        migrations.AlterModelOptions(
            name='kindrep',
            options={'verbose_name': 'Tipo Reporte', 'verbose_name_plural': 'Tipo Reportes'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='responce',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='roomstate',
            options={'verbose_name': 'Estado Habitación', 'verbose_name_plural': 'Estado Habitaciones'},
        ),
    ]
