# Generated by Django 3.2.7 on 2021-09-24 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0003_auto_20210924_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='get_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de recivo'),
        ),
    ]
