# Generated by Django 3.2.7 on 2021-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0004_alter_report_get_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='response_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
    ]
