# Generated by Django 3.2.7 on 2021-09-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_alter_report_response_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='responsed',
            field=models.BooleanField(default=False, verbose_name='Resuelto'),
        ),
        migrations.AlterField(
            model_name='report',
            name='responce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='express.responce'),
        ),
    ]
