# Generated by Django 3.2.7 on 2021-10-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0008_rename_last_names_executive_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendants',
            old_name='last_names',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_names',
            new_name='last_name',
        ),
    ]
